// Mocks generated by Mockito 5.4.5 from annotations
// in flowery_app/test/features/categories/data/repository_imp/getCategories_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flowery_app/core/network/common/api_result.dart' as _i4;
import 'package:flowery_app/features/categories/data/data_source/getCategories_data_source.dart'
    as _i2;
import 'package:flowery_app/features/categories/domain/entity/get_all_categories_entity.dart'
    as _i5;
import 'package:flowery_app/features/categories/domain/entity/get_products_by_id_entity.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [GetAllCategoriesDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAllCategoriesDataSource extends _i1.Mock
    implements _i2.GetAllCategoriesDataSource {
  MockGetAllCategoriesDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i5.GetAllCategoriesEntity>> getAllCategories() =>
      (super.noSuchMethod(
            Invocation.method(#getAllCategories, []),
            returnValue:
                _i3.Future<_i4.Result<_i5.GetAllCategoriesEntity>>.value(
                  _i6.dummyValue<_i4.Result<_i5.GetAllCategoriesEntity>>(
                    this,
                    Invocation.method(#getAllCategories, []),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<_i5.GetAllCategoriesEntity>>);

  @override
  _i3.Future<_i4.Result<_i7.ProductsOfCategoryResponseEntity>> getProductsById(
    String? categoryId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getProductsById, [categoryId]),
            returnValue: _i3.Future<
              _i4.Result<_i7.ProductsOfCategoryResponseEntity>
            >.value(
              _i6.dummyValue<_i4.Result<_i7.ProductsOfCategoryResponseEntity>>(
                this,
                Invocation.method(#getProductsById, [categoryId]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i7.ProductsOfCategoryResponseEntity>>);

  @override
  _i3.Future<_i4.Result<_i7.ProductsOfCategoryResponseEntity>> filterToProducts(
    String? categoryId,
    String? sort,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#filterToProducts, [categoryId, sort]),
            returnValue: _i3.Future<
              _i4.Result<_i7.ProductsOfCategoryResponseEntity>
            >.value(
              _i6.dummyValue<_i4.Result<_i7.ProductsOfCategoryResponseEntity>>(
                this,
                Invocation.method(#filterToProducts, [categoryId, sort]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i7.ProductsOfCategoryResponseEntity>>);
}
