// Mocks generated by Mockito 5.4.5 from annotations
// in flowery_app/test/features/categories/data/repository_imp/getCategories_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:flowery_app/features/categories/data/data_source/getCategories_data_source.dart'
    as _i4;
import 'package:flowery_app/features/categories/domain/entity/get_all_categories_entity.dart'
    as _i2;
import 'package:flowery_app/features/categories/domain/entity/get_products_by_id_entity.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeGetAllCategoriesEntity_0 extends _i1.SmartFake
    implements _i2.GetAllCategoriesEntity {
  _FakeGetAllCategoriesEntity_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProductsModelEntity_1 extends _i1.SmartFake
    implements _i3.ProductsModelEntity {
  _FakeProductsModelEntity_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetAllCategoriesDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetAllCategoriesDataSource extends _i1.Mock
    implements _i4.GetAllCategoriesDataSource {
  MockGetAllCategoriesDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.GetAllCategoriesEntity> getAllCategories() =>
      (super.noSuchMethod(
            Invocation.method(#getAllCategories, []),
            returnValue: _i5.Future<_i2.GetAllCategoriesEntity>.value(
              _FakeGetAllCategoriesEntity_0(
                this,
                Invocation.method(#getAllCategories, []),
              ),
            ),
          )
          as _i5.Future<_i2.GetAllCategoriesEntity>);

  @override
  _i5.Future<_i3.ProductsModelEntity> getProductsById(String? categoryId) =>
      (super.noSuchMethod(
            Invocation.method(#getProductsById, [categoryId]),
            returnValue: _i5.Future<_i3.ProductsModelEntity>.value(
              _FakeProductsModelEntity_1(
                this,
                Invocation.method(#getProductsById, [categoryId]),
              ),
            ),
          )
          as _i5.Future<_i3.ProductsModelEntity>);
}
