// Mocks generated by Mockito 5.4.5 from annotations
// in flowery_app/test/features/search/domain/usecase/search_query_use_case_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flowery_app/core/network/common/api_result.dart' as _i4;
import 'package:flowery_app/features/home/domain/entity/prodect_entity.dart'
    as _i5;
import 'package:flowery_app/features/search/domain/repository/search_query_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [SearchQueryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchQueryRepository extends _i1.Mock
    implements _i2.SearchQueryRepository {
  MockSearchQueryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<List<_i5.ProductItemEntity>>> getProductsByQuery(
    String? query,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getProductsByQuery, [query]),
            returnValue:
                _i3.Future<_i4.Result<List<_i5.ProductItemEntity>>>.value(
                  _i6.dummyValue<_i4.Result<List<_i5.ProductItemEntity>>>(
                    this,
                    Invocation.method(#getProductsByQuery, [query]),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<List<_i5.ProductItemEntity>>>);
}
