// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDARNAK0i1H-TIhztJFFtSzUaGT-MNYZUo',
    appId: '1:540937284318:web:3d6d45e288902332bff04f',
    messagingSenderId: '540937284318',
    projectId: 'floweryapp-63022',
    authDomain: 'floweryapp-63022.firebaseapp.com',
    storageBucket: 'floweryapp-63022.firebasestorage.app',
    measurementId: 'G-CZBRVX239D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6zH-fwsfP9-IarD2V6OQ7Egtk4eNtK64',
    appId: '1:540937284318:android:61e4e1e98fbe7a85bff04f',
    messagingSenderId: '540937284318',
    projectId: 'floweryapp-63022',
    storageBucket: 'floweryapp-63022.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvhuBRrpeGZP3t2gucAX-CqZC7_Jhsabw',
    appId: '1:540937284318:ios:b6507dfc92fc90acbff04f',
    messagingSenderId: '540937284318',
    projectId: 'floweryapp-63022',
    storageBucket: 'floweryapp-63022.firebasestorage.app',
    iosBundleId: 'com.example.floweryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvhuBRrpeGZP3t2gucAX-CqZC7_Jhsabw',
    appId: '1:540937284318:ios:b6507dfc92fc90acbff04f',
    messagingSenderId: '540937284318',
    projectId: 'floweryapp-63022',
    storageBucket: 'floweryapp-63022.firebasestorage.app',
    iosBundleId: 'com.example.floweryApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDARNAK0i1H-TIhztJFFtSzUaGT-MNYZUo',
    appId: '1:540937284318:web:80bafd93ecc7cd41bff04f',
    messagingSenderId: '540937284318',
    projectId: 'floweryapp-63022',
    authDomain: 'floweryapp-63022.firebaseapp.com',
    storageBucket: 'floweryapp-63022.firebasestorage.app',
    measurementId: 'G-EKB207RYMM',
  );

}