// Mocks generated by Mockito 5.4.5 from annotations
// in flowery_app/test/features/profile/domain/usecase/change_password_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flowery_app/core/network/common/api_result.dart' as _i4;
import 'package:flowery_app/features/profile/domain/entity/change_password/change_password__request_entity.dart'
    as _i6;
import 'package:flowery_app/features/profile/domain/entity/change_password/change_password__response_entity.dart'
    as _i5;
import 'package:flowery_app/features/profile/domain/entity/profile_data_entity/profile_data_entity.dart'
    as _i8;
import 'package:flowery_app/features/profile/domain/repository/profile_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [ProfileRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockProfileRepository extends _i1.Mock implements _i2.ProfileRepository {
  MockProfileRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i5.ChangePasswordResponseEntity?>> changePassword(
    _i6.ChangePasswordRequestEntity? passwordData,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#changePassword, [passwordData]),
            returnValue:
                _i3.Future<_i4.Result<_i5.ChangePasswordResponseEntity?>>.value(
                  _i7.dummyValue<_i4.Result<_i5.ChangePasswordResponseEntity?>>(
                    this,
                    Invocation.method(#changePassword, [passwordData]),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<_i5.ChangePasswordResponseEntity?>>);

  @override
  _i3.Future<_i4.Result<_i8.ProfileDataEntity>> getProfileData() =>
      (super.noSuchMethod(
            Invocation.method(#getProfileData, []),
            returnValue: _i3.Future<_i4.Result<_i8.ProfileDataEntity>>.value(
              _i7.dummyValue<_i4.Result<_i8.ProfileDataEntity>>(
                this,
                Invocation.method(#getProfileData, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i8.ProfileDataEntity>>);

  @override
  _i3.Future<_i4.Result<void>> deleteAddress(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAddress, [id]),
            returnValue: _i3.Future<_i4.Result<void>>.value(
              _i7.dummyValue<_i4.Result<void>>(
                this,
                Invocation.method(#deleteAddress, [id]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<void>>);
}
