name: flutter-test-action

on:
  push:
  pull_request:

jobs:
  flutter-test-action:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: 3.27.4

      - name: Validate PR title format
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const core = require('@actions/core');  # Only declare once
            const { context } = require('@actions/github');

            const prTitle = context.payload.pull_request.title;

            const titleRegex = /^(feat|fix|hotfix|release|build|test)\((ECOM-\d+|JIRA-\d+|[A-Z]+-\d+)\):\s.+$/;

            if (!titleRegex.test(prTitle)) {
              core.setFailed(`❌ Invalid PR title: "${prTitle}"

            Expected format:
              type(SCOPE-ID): task name
            Example:
              feat(ECOM-123): Add user login flow
            Allowed types: feat, fix, hotfix, release, build, test`);
            } else {
              console.log("✅ PR title is valid.");
            }

      - run: flutter --version
      - run: flutter pub get

      - name: Run test
        run: flutter test

      - name: Validate branch name
        run: |
          BRANCH_NAME="${{ steps.branch.outputs.name }}"
          echo "Checking branch: $BRANCH_NAME"

      # Build APK
      - name: Build release APK
        run: flutter build apk --release

      # Upload to Firebase App Distribution
      - name: Upload to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          file: build/app/outputs/flutter-apk/app-release.apk
          testers: esammww.com@gmail.com
          releaseNotes: "🚀 Auto-release from GitHub Actions"